FROM debian:12

ENV DEBIAN_FRONTEND=noninteractive

### Wine and x86/64 emulation on arm

# Install box86/box64
# From https://github.com/Pi-Apps-Coders/box86-debs and https://github.com/Pi-Apps-Coders/box64-debs
# (note: for 32bit host, you must change command for installing box86)
RUN printf "Types: deb\nURIs: http://Pi-Apps-Coders.github.io/box86-debs/debian\nSuites: ./\nAllow-Insecure: yes\nTrusted: yes\n" > /etc/apt/sources.list.d/box86.sources && \
    printf "Types: deb\nURIs: http://Pi-Apps-Coders.github.io/box64-debs/debian\nSuites: ./\nAllow-Insecure: yes\nTrusted: yes\n" > /etc/apt/sources.list.d/box64.sources && \
    dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -y --no-install-recommends box86-generic-arm:armhf box64-generic-arm

# Install wine
# From https://github.com/ptitSeb/box64/blob/main/docs/X64WINE.md
ARG branch=stable version=7.0.2 id=debian dist=bookworm tag=-1
#ARG branch=stable version=10.0.0.0 id=debian dist=bookworm tag=-1
#ARG branch=staging version=10.3 id=debian dist=bookworm tag=-1
RUN apt-get install -y wget && \
    wget -q \
        "http://dl.winehq.org/wine-builds/${id}/dists/${dist}/main/binary-amd64/wine-${branch}-amd64_${version}~${dist}${tag}_amd64.deb" \
        "http://dl.winehq.org/wine-builds/${id}/dists/${dist}/main/binary-amd64/wine-${branch}_${version}~${dist}${tag}_amd64.deb" \
        "http://dl.winehq.org/wine-builds/${id}/dists/${dist}/main/binary-i386/wine-${branch}-i386_${version}~${dist}${tag}_i386.deb" && \
    for i in wine*.deb; do dpkg-deb -x "$i" wine-installer; done && \
    mv wine-installer/opt/wine* /wine && \
    rm -rf wine-installer

# line 2: cabextract for winetricks to install most libs, xvfb to run gui programs
# line 3: needed for running box86/wine-i386 on a 64-bit RPiOS via multiarch
# line 4: needed for running box86/wine-i386 on a 64-bit RPiOS via multiarch
# line 5-8: needed for running wine-staging on RPiOS (Credits: chills340)
RUN apt-get install -y \
        cabextract xvfb \
        $(dpkg-deb -f "wine-${branch}-i386"*.deb  Depends Recommends | sed 's/^[^ ]*: //; s/\( [(|][^,]*\)*\($\|,\)/:armhf/g; s/libtiff5/libtiff6/') \
        $(dpkg-deb -f "wine-${branch}-amd64"*.deb Depends Recommends | sed 's/^[^ ]*: //; s/\( [(|][^,]*\)*\($\|,\)/:arm64/g; s/libtiff5/libtiff6/') \
        libstb0 && \
    wget 'http://ftp.us.debian.org/debian/pool/main/f/faudio/libfaudio0_21.02-1~bpo10+1_i386.deb' && \
    dpkg-deb -xv libfaudio0_*~bpo10+1_i386.deb libfaudio && \
    cp -TRv libfaudio/usr/ /usr/ && \
    rm -rf *.deb libfaudio/

RUN printf '#!/bin/sh\nbox86 /wine/bin/wine       "$@"' > /usr/local/bin/wine       && \
    printf '#!/bin/sh\nbox64 /wine/bin/wine64     "$@"' > /usr/local/bin/wine64     && \
    printf '#!/bin/sh\nbox64 /wine/bin/wineserver "$@"' > /usr/local/bin/wineserver && \
    ln -s /wine/bin/winecfg  /usr/local/bin/winecfg  && \
    ln -s /wine/bin/wineboot /usr/local/bin/wineboot && \
    chmod +x /usr/local/bin/wine*

# Install winetricks
RUN wget -P /usr/local/bin/ https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks && \
    chmod +x /usr/local/bin/winetricks


### Voiceroid

# Install
RUN apt-get install -y --no-install-recommends --no-install-suggests \
        tightvncserver xautomation xsel xfonts-base procps python3 sox libsox-fmt-mp3

ENV USER=root
ADD assets/root1/ /root/
# chown/chmod is needed for programs to create config dir etc
RUN chown -R root /root/.vnc/ && chmod 0755 /root/.vnc/xstartup && chmod 0600 /root/.vnc/passwd
ADD assets/root2/ /root/
WORKDIR /root/
ENTRYPOINT ["/root/entrypoint.sh"]

# vim: ft=dockerfile
