# Credit: https://github.com/dirtboll/winebox64

FROM debian:bookworm-slim AS build

ENV DEBIAN_FRONTEND="noninteractive"

# Install libraries needed to compile box
RUN dpkg --add-architecture armhf \
 && apt-get update \
 && apt-get install -y --no-install-recommends --no-install-suggests git wget curl cmake python3 build-essential gcc-arm-linux-gnueabihf libc6-dev-armhf-cross libc6:armhf libstdc++6:armhf     

WORKDIR /root

# In the following, "git clone ..." followed by "git checkout ..." are replaced with commands with the same effect but only fetches necessary commit.
# Also -j$(nproc) is replaced by -j1 to avoid memory exhaustion

# Build box86
RUN mkdir box86 && cd box86 && git -c init.defaultBranch=master init && git remote add origin https://github.com/ptitSeb/box86 && git -c http.sslVerify=false fetch --depth 1 origin v0.3.8 && git -c advice.detachedHead=false checkout FETCH_HEAD && cd .. \
 && mkdir box86/build \
 && cd box86/build \
 && cmake .. -DRPI4ARM64=1 -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo \
 && make -j1 \
 && make install DESTDIR=/box 

# Build box64
# same as "git clone ..." followed by "git checkout ..." but network efficient
RUN mkdir box64 && cd box64 && git -c init.defaultBranch=master init && git remote add origin https://github.com/ptitSeb/box64 && git -c http.sslVerify=false fetch --depth 1 origin v0.3.4 && git -c advice.detachedHead=false checkout FETCH_HEAD && cd .. \
 && mkdir box64/build \
 && cd box64/build \
 && cmake .. -DRPI4ARM64=1 -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo \
 && make -j1 \
 && make install DESTDIR=/box

FROM debian:bookworm-slim

# Copy compiled box86 and box64 binaries
COPY --from=build /box /

# Install libraries needed to run box
RUN dpkg --add-architecture armhf \
 && apt-get update \
 && apt-get install --yes --no-install-recommends wget curl libc6:armhf libstdc++6:armhf ca-certificates 

# `cabextract` is needed by winetricks to install most libraries
# `xvfb` is needed in wine to spawn display window because some Windows program can't run without it (using `xvfb-run`)
# If you are sure you don't need it, feel free to remove
RUN apt install -y cabextract xvfb

# Clean up
RUN apt-get -y autoremove \
 && apt-get clean autoclean \
 && rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists

# Install wine, wine64, and winetricks
COPY install-wine.sh /
RUN http_proxy=$http_proxy bash /install-wine.sh \
 && rm /install-wine.sh

# Install box wrapper for wine
COPY wrap-wine.sh /
RUN bash /wrap-wine.sh \
 && rm /wrap-wine.sh

WORKDIR /root
ENTRYPOINT ["bash", "-c"]
CMD ["bash"]

# vim: ft=dockerfile
